/* GENERATED by scripts/build-template-stories.mjs — do not edit.
   One story per page template in design-kit/templates/, rendering that exact file so Storybook
   and the design kit always show the same page. Re-run: npm run build:templates */
import type { Meta, StoryObj } from '@storybook/react';
import { LiveTemplate } from './LiveTemplate';

const meta: Meta<typeof LiveTemplate> = {
  title: 'Templates/Pages',
  component: LiveTemplate,
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'The page templates from `design-kit/templates/`. Each story renders the template file itself, so it matches the design kit exactly — **Live capture** pages are frozen copies of dubizzle.com.eg and render like production. Switch **device** between desktop (1440px) and mobile (390px); the frame is scaled to fit. Copy the HTML file to start feature work.',
      },
    },
  },
  argTypes: {
    device: { control: 'inline-radio', options: ['desktop', 'mobile'] },
    name: { table: { disable: true } },
    label: { table: { disable: true } },
    layouts: { table: { disable: true } },
    live: { table: { disable: true } },
    local: { table: { disable: true } },
    captured: { table: { disable: true } },
    origin: { table: { disable: true } },
  },
  args: { device: 'desktop' },
};
export default meta;

type Story = StoryObj<typeof LiveTemplate>;

export const Home: Story = {
  name: "Home",
  args: {
    "name": "home",
    "label": "Home",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/"
  },
};

export const Motors: Story = {
  name: "Motors landing",
  args: {
    "name": "motors",
    "label": "Motors landing",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/motors/"
  },
};

export const Properties: Story = {
  name: "All properties listing (/en/properties/)",
  args: {
    "name": "properties",
    "label": "All properties listing (/en/properties/)",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/properties/"
  },
};

export const CarFinance: Story = {
  name: "Car finance",
  args: {
    "name": "car-finance",
    "label": "Car finance",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/motors/car-finance/"
  },
};

export const Search: Story = {
  name: "Search results — cars",
  args: {
    "name": "search",
    "label": "Search results — cars",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/vehicles/cars-for-sale/"
  },
};

export const SearchProperty: Story = {
  name: "Search results — property",
  args: {
    "name": "search-property",
    "label": "Search results — property",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/"
  },
};

export const SearchMobiles: Story = {
  name: "Search results — mobile phones",
  args: {
    "name": "search-mobiles",
    "label": "Search results — mobile phones",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/mobile-phones-tablets-accessories-numbers/mobile-phones/"
  },
};

export const AdDetail: Story = {
  name: "Ad detail — car",
  args: {
    "name": "ad-detail",
    "label": "Ad detail — car",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/ad/mercedes-benz-e300-2018-amg-ID208928385.html"
  },
};

export const AdDetailProperty: Story = {
  name: "Ad detail — property",
  args: {
    "name": "ad-detail-property",
    "label": "Ad detail — property",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/ad/penthouse-167-m2-fully-finished-with-acs-ready-to-move-for-sale-in-fifth-square-al-marasem-new-cairo-ID504003995.html"
  },
};

export const AdDetailMobilePhone: Story = {
  name: "Ad detail — mobile phone",
  args: {
    "name": "ad-detail-mobile-phone",
    "label": "Ad detail — mobile phone",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/ad/honor-robot-phone-1-tera-16g-ram-ID208912587.html"
  },
};

export const SellerPage: Story = {
  name: "Seller / business profile",
  args: {
    "name": "seller-page",
    "label": "Seller / business profile",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/companies/Smart-Car-6610"
  },
};

export const Login: Story = {
  name: "Login or sign up (dialog)",
  args: {
    "name": "login",
    "label": "Login or sign up (dialog)",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/"
  },
};

export const NotFound: Story = {
  name: "Not found (404)",
  args: {
    "name": "not-found",
    "label": "Not found (404)",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/this-page-does-not-exist-404/"
  },
};

export const MyAds: Story = {
  name: "My ads",
  args: {
    "name": "my-ads",
    "label": "My ads",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const Chat: Story = {
  name: "Chats",
  args: {
    "name": "chat",
    "label": "Chats",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const EditProfile: Story = {
  name: "Edit profile",
  args: {
    "name": "edit-profile",
    "label": "Edit profile",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const SettingsPrivacy: Story = {
  name: "Settings — privacy",
  args: {
    "name": "settings-privacy",
    "label": "Settings — privacy",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const SettingsNotifications: Story = {
  name: "Settings — notifications",
  args: {
    "name": "settings-notifications",
    "label": "Settings — notifications",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const Packages: Story = {
  name: "Business packages",
  args: {
    "name": "packages",
    "label": "Business packages",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const PostAdCategory: Story = {
  name: "Post an ad — choose category",
  args: {
    "name": "post-ad-category",
    "label": "Post an ad — choose category",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const PostAdSubcategory: Story = {
  name: "Post an ad — choose subcategory",
  args: {
    "name": "post-ad-subcategory",
    "label": "Post an ad — choose subcategory",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const PostAd: Story = {
  name: "Post an ad — details form (empty)",
  args: {
    "name": "post-ad",
    "label": "Post an ad — details form (empty)",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const PostAdFilled: Story = {
  name: "Post an ad — details form (filled, never posted)",
  args: {
    "name": "post-ad-filled",
    "label": "Post an ad — details form (filled, never posted)",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const UpsellSelect: Story = {
  name: "Upselling — choose category",
  args: {
    "name": "upsell-select",
    "label": "Upselling — choose category",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const Upsell: Story = {
  name: "Upselling — packages",
  args: {
    "name": "upsell",
    "label": "Upselling — packages",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const PropertyLanding: Story = {
  name: "Property landing — the vertical (/en/realestate/)",
  args: {
    "name": "property-landing",
    "label": "Property landing — the vertical (/en/realestate/)",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/realestate/"
  },
};

export const VehiclesListing: Story = {
  name: "All vehicles listing (/en/vehicles/)",
  args: {
    "name": "vehicles-listing",
    "label": "All vehicles listing (/en/vehicles/)",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/vehicles/"
  },
};

export const NewCars: Story = {
  name: "New Cars — catalogue",
  args: {
    "name": "new-cars",
    "label": "New Cars — catalogue",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/motors/new-cars/"
  },
};

export const NewCarsBrand: Story = {
  name: "New Cars — brand",
  args: {
    "name": "new-cars-brand",
    "label": "New Cars — brand",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/motors/new-cars/toyota/"
  },
};

export const NewCarsModel: Story = {
  name: "New Cars — model (price, variants)",
  args: {
    "name": "new-cars-model",
    "label": "New Cars — model (price, variants)",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/motors/new-cars/toyota/corolla/"
  },
};

export const CarComparison: Story = {
  name: "Car comparison tool",
  args: {
    "name": "car-comparison",
    "label": "Car comparison tool",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/motors/new-cars/compare/"
  },
};

export const ElectricCars: Story = {
  name: "Electric cars landing",
  args: {
    "name": "electric-cars",
    "label": "Electric cars landing",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/motors/electric-cars/"
  },
};

export const SearchCarsModel: Story = {
  name: "Search results — cars, brand + model",
  args: {
    "name": "search-cars-model",
    "label": "Search results — cars, brand + model",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/vehicles/cars-for-sale/mercedes-benz/model-c180/"
  },
};

export const SearchMotorcycles: Story = {
  name: "Search results — motorcycles",
  args: {
    "name": "search-motorcycles",
    "label": "Search results — motorcycles",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/vehicles/motorcycles-accessories/"
  },
};

export const SearchTrucks: Story = {
  name: "Search results — trucks & buses",
  args: {
    "name": "search-trucks",
    "label": "Search results — trucks & buses",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/vehicles/trucks-buses-other-vehicles/"
  },
};

export const SearchPropertyRent: Story = {
  name: "Search results — property for rent",
  args: {
    "name": "search-property-rent",
    "label": "Search results — property for rent",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-rent/"
  },
};

export const SearchPropertyCommercial: Story = {
  name: "Search results — commercial property",
  args: {
    "name": "search-property-commercial",
    "label": "Search results — commercial property",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/properties/commercial-for-sale/"
  },
};

export const SearchPropertyVacation: Story = {
  name: "Search results — chalets & vacation homes",
  args: {
    "name": "search-property-vacation",
    "label": "Search results — chalets & vacation homes",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/properties/vacation-homes-for-sale/"
  },
};

export const SearchPropertyLand: Story = {
  name: "Search results — buildings & land",
  args: {
    "name": "search-property-land",
    "label": "Search results — buildings & land",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/properties/buildings-lands-other/"
  },
};

export const PropertyCompound: Story = {
  name: "Compound page",
  args: {
    "name": "property-compound",
    "label": "Compound page",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/properties/mivida-compound/"
  },
};

export const PropertyArea: Story = {
  name: "Property area page",
  args: {
    "name": "property-area",
    "label": "Property area page",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/properties/new-cairo/"
  },
};

export const AgencyPage: Story = {
  name: "Property agency profile",
  args: {
    "name": "agency-page",
    "label": "Property agency profile",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/companies/gate-real-estate-602"
  },
};

export const AdDetailPropertyRent: Story = {
  name: "Ad detail — property for rent",
  args: {
    "name": "ad-detail-property-rent",
    "label": "Ad detail — property for rent",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-16",
    "origin": "https://www.dubizzle.com.eg/en/ad/fully-furnished-first-use-apartment-for-rent-in-villette-sky-condos-180-sqm-3-bedrooms-egp-100000-ID504099029.html"
  },
};

export const AgencyPortal: Story = {
  name: "Agency portal",
  args: {
    "name": "agency-portal",
    "label": "Agency portal",
    "layouts": [
      "desktop"
    ],
    "live": false
  },
};

export const Favourites: Story = {
  name: "Favourites",
  args: {
    "name": "favourites",
    "label": "Favourites",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": false
  },
};

export const Payment: Story = {
  name: "Payment",
  args: {
    "name": "payment",
    "label": "Payment",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": false
  },
};
