/* GENERATED by scripts/build-template-stories.mjs — do not edit.
   One story per page template in design-kit/templates/, rendering that exact file so Storybook
   and the design kit always show the same page. Re-run: npm run build:templates */
import type { Meta, StoryObj } from '@storybook/react';
import { LiveTemplate } from './LiveTemplate';

const meta: Meta<typeof LiveTemplate> = {
  title: 'Templates/Pages',
  component: LiveTemplate,
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component:
          'The page templates from `design-kit/templates/`. Each story renders the template file itself, so it matches the design kit exactly — **Live capture** pages are frozen copies of dubizzle.com.eg and render like production. Switch **device** between desktop (1440px) and mobile (390px); the frame is scaled to fit. Copy the HTML file to start feature work.',
      },
    },
  },
  argTypes: {
    device: { control: 'inline-radio', options: ['desktop', 'mobile'] },
    name: { table: { disable: true } },
    label: { table: { disable: true } },
    layouts: { table: { disable: true } },
    live: { table: { disable: true } },
    local: { table: { disable: true } },
    captured: { table: { disable: true } },
    origin: { table: { disable: true } },
  },
  args: { device: 'desktop' },
};
export default meta;

type Story = StoryObj<typeof LiveTemplate>;

export const Home: Story = {
  name: "Home",
  args: {
    "name": "home",
    "label": "Home",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/"
  },
};

export const Motors: Story = {
  name: "Motors landing",
  args: {
    "name": "motors",
    "label": "Motors landing",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/motors/"
  },
};

export const Properties: Story = {
  name: "Properties landing",
  args: {
    "name": "properties",
    "label": "Properties landing",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/properties/"
  },
};

export const CarFinance: Story = {
  name: "Car finance",
  args: {
    "name": "car-finance",
    "label": "Car finance",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/motors/car-finance/"
  },
};

export const Search: Story = {
  name: "Search results — cars",
  args: {
    "name": "search",
    "label": "Search results — cars",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/vehicles/cars-for-sale/"
  },
};

export const SearchProperty: Story = {
  name: "Search results — property",
  args: {
    "name": "search-property",
    "label": "Search results — property",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/"
  },
};

export const SearchMobiles: Story = {
  name: "Search results — mobile phones",
  args: {
    "name": "search-mobiles",
    "label": "Search results — mobile phones",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/mobile-phones-tablets-accessories-numbers/mobile-phones/"
  },
};

export const AdDetail: Story = {
  name: "Ad detail — car",
  args: {
    "name": "ad-detail",
    "label": "Ad detail — car",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/ad/mercedes-benz-e300-2018-amg-ID208928385.html"
  },
};

export const AdDetailProperty: Story = {
  name: "Ad detail — property",
  args: {
    "name": "ad-detail-property",
    "label": "Ad detail — property",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/ad/penthouse-167-m2-fully-finished-with-acs-ready-to-move-for-sale-in-fifth-square-al-marasem-new-cairo-ID504003995.html"
  },
};

export const AdDetailMobilePhone: Story = {
  name: "Ad detail — mobile phone",
  args: {
    "name": "ad-detail-mobile-phone",
    "label": "Ad detail — mobile phone",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/ad/honor-robot-phone-1-tera-16g-ram-ID208912587.html"
  },
};

export const SellerPage: Story = {
  name: "Seller / business profile",
  args: {
    "name": "seller-page",
    "label": "Seller / business profile",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/companies/Smart-Car-6610"
  },
};

export const Login: Story = {
  name: "Login or sign up (dialog)",
  args: {
    "name": "login",
    "label": "Login or sign up (dialog)",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/"
  },
};

export const NotFound: Story = {
  name: "Not found (404)",
  args: {
    "name": "not-found",
    "label": "Not found (404)",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg/en/this-page-does-not-exist-404/"
  },
};

export const MyAds: Story = {
  name: "My ads",
  args: {
    "name": "my-ads",
    "label": "My ads",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const Chat: Story = {
  name: "Chats",
  args: {
    "name": "chat",
    "label": "Chats",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const EditProfile: Story = {
  name: "Edit profile",
  args: {
    "name": "edit-profile",
    "label": "Edit profile",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const SettingsPrivacy: Story = {
  name: "Settings — privacy",
  args: {
    "name": "settings-privacy",
    "label": "Settings — privacy",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const SettingsNotifications: Story = {
  name: "Settings — notifications",
  args: {
    "name": "settings-notifications",
    "label": "Settings — notifications",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const Packages: Story = {
  name: "Business packages",
  args: {
    "name": "packages",
    "label": "Business packages",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const PostAdCategory: Story = {
  name: "Post an ad — choose category",
  args: {
    "name": "post-ad-category",
    "label": "Post an ad — choose category",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const PostAdSubcategory: Story = {
  name: "Post an ad — choose subcategory",
  args: {
    "name": "post-ad-subcategory",
    "label": "Post an ad — choose subcategory",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const PostAd: Story = {
  name: "Post an ad — details form (empty)",
  args: {
    "name": "post-ad",
    "label": "Post an ad — details form (empty)",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const PostAdFilled: Story = {
  name: "Post an ad — details form (filled, never posted)",
  args: {
    "name": "post-ad-filled",
    "label": "Post an ad — details form (filled, never posted)",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const UpsellSelect: Story = {
  name: "Upselling — choose category",
  args: {
    "name": "upsell-select",
    "label": "Upselling — choose category",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const Upsell: Story = {
  name: "Upselling — packages",
  args: {
    "name": "upsell",
    "label": "Upselling — packages",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": true,
    "local": true,
    "captured": "2026-09-14",
    "origin": "https://www.dubizzle.com.eg"
  },
};

export const AgencyPortal: Story = {
  name: "Agency portal",
  args: {
    "name": "agency-portal",
    "label": "Agency portal",
    "layouts": [
      "desktop"
    ],
    "live": false
  },
};

export const Favourites: Story = {
  name: "Favourites",
  args: {
    "name": "favourites",
    "label": "Favourites",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": false
  },
};

export const Payment: Story = {
  name: "Payment",
  args: {
    "name": "payment",
    "label": "Payment",
    "layouts": [
      "desktop",
      "mobile"
    ],
    "live": false
  },
};
