#!/usr/bin/env node
/**
 * Builds design-kit/index.html — the visual reference for the design system.
 *
 * Storybook covers the React library for engineers; this is the designer-facing
 * view: one page, no build, no node_modules, open it in any browser. The token
 * sections are generated from tokens.json so the palette and scales can't drift
 * from what the components actually use.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(ROOT, 'design-kit/tokens/tokens.json'), 'utf8'));
const icons = JSON.parse(readFileSync(join(ROOT, 'design-kit/icons/icons.json'), 'utf8'));

const colorTokens = tokens.groups.color ?? {};

/** Resolves a `var(--x)` chain down to a literal so swatches can be painted. */
function literal(value, depth = 0) {
  if (depth > 10 || typeof value !== 'string') return value;
  const match = value.match(/^var\((--[a-z0-9-]+)\)$/);
  if (!match) return value;
  const target = colorTokens[match[1]] ?? tokens.groups.spacing?.[match[1]] ?? tokens.groups.radius?.[match[1]];
  return target ? literal(target, depth + 1) : value;
}

/** Dark swatches need light labels. */
function isDark(hex) {
  const m = String(hex).match(/^#([0-9a-f]{6})$/i);
  if (!m) return false;
  const n = parseInt(m[1], 16);
  const [r, g, b] = [(n >> 16) & 255, (n >> 8) & 255, n & 255];
  return 0.2126 * r + 0.7152 * g + 0.0722 * b < 140;
}

const SCALES = [
  ['Red — primary', /^--red-\d+$/],
  ['Gray — neutral', /^--gray-\d+$/],
  ['Blue', /^--blue-\d+$/],
  ['Yellow', /^--yellow-\d+$/],
  ['Green', /^--green-\d+$/],
];

const SEMANTIC_COLORS = [
  ['--color-primary', 'Brand, CTAs, active states'],
  ['--color-primary-hover', 'Primary button hover'],
  ['--color-primary-active', 'Primary button pressed'],
  ['--color-secondary', 'Links, info, secondary actions'],
  ['--color-success', 'Success, verified'],
  ['--color-warning', 'Warning, Featured accent'],
  ['--color-error', 'Errors, destructive'],
  ['--text-primary', 'Body text'],
  ['--text-secondary', 'Labels, secondary text'],
  ['--text-tertiary', 'Placeholder, meta, disabled'],
  ['--surface-page', 'Page background'],
  ['--surface-subtle', 'Section background'],
  ['--surface-muted', 'Muted background'],
  ['--border-default', 'Default borders'],
  ['--border-input', 'Input borders'],
];

function swatchGrid(entries) {
  return entries
    .map(([name, note]) => {
      const raw = colorTokens[name];
      if (raw === undefined) return '';
      const value = literal(raw);
      return `<figure class="sw">
        <div class="sw__chip${isDark(value) ? ' sw__chip--dark' : ''}" style="background:var(${name})">${value}</div>
        <figcaption><code>${name}</code>${note ? `<span>${note}</span>` : ''}</figcaption>
      </figure>`;
    })
    .join('\n');
}

const colorSections = SCALES.map(([label, pattern]) => {
  const entries = Object.keys(colorTokens)
    .filter((n) => pattern.test(n))
    .sort()
    .map((n) => [n, '']);
  return `<h3>${label}</h3>\n<div class="sw-grid">\n${swatchGrid(entries)}\n</div>`;
}).join('\n');

const TYPE_SIZES = ['--text-xs', '--text-sm', '--text-md', '--text-lg', '--text-xl', '--text-2xl', '--text-3xl'];
const WEIGHTS = [
  ['--weight-regular', 'Regular'],
  ['--weight-semibold', 'Semibold'],
  ['--weight-bold', 'Bold'],
];
const SPACES = ['--space-1', '--space-2', '--space-3', '--space-4', '--space-5', '--space-6', '--space-7', '--space-8', '--space-9', '--space-10'];
const RADII = [
  ['--radius-sm', 'Small elements'],
  ['--radius-md', 'Inputs, buttons'],
  ['--radius-lg', 'Cards, sections'],
  ['--radius-xl', 'Dropdowns'],
  ['--radius-pill', 'Pills, tags'],
];
const SHADOWS = [
  ['--shadow-card', 'Card at rest'],
  ['--shadow-card-hover', 'Card hover'],
  ['--shadow-dropdown', 'Dropdown menus'],
  ['--shadow-control', 'Small controls'],
];

const resolvedSpacing = (name) =>
  literal(tokens.groups.spacing?.[name] ?? '') || tokens.groups.spacing?.[name] || '';

const sampleIcons = Object.entries(icons.categories)
  .flatMap(([category, list]) => list.slice(0, 6).map((i) => ({ ...i, category })))
  .slice(0, 24);

const page = `<!doctype html>
<!-- GENERATED by scripts/build-preview.mjs — rebuild with: npm run build:preview -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>dubizzle Egypt — Design System</title>
<link rel="stylesheet" href="tokens/tokens.css">
<link rel="stylesheet" href="patterns/patterns.css">
<style>
  body { background: var(--surface-page); }
  .shell { display: grid; grid-template-columns: 24rem minmax(0, 1fr); gap: var(--space-8); max-width: 148rem; margin-inline: auto; padding: 0 var(--space-6); }
  .nav { position: sticky; top: 0; align-self: start; height: 100vh; overflow-y: auto; padding-block: var(--space-6); }
  .nav__brand { display: flex; align-items: center; gap: var(--space-2); margin-bottom: var(--space-6); }
  .nav__brand img { height: 3.2rem; }
  .nav a { display: block; padding: 0.6rem var(--space-2); border-radius: var(--radius-md); font-size: var(--text-sm); color: var(--text-secondary); }
  .nav a:hover { background: var(--surface-subtle); color: var(--text-primary); }
  .nav hr { border: none; border-top: 0.1rem solid var(--border-default); margin: var(--space-3) 0; }
  .doc { padding-block: var(--space-8) var(--space-10); min-width: 0; }
  .doc > section { padding-block: var(--space-6); border-top: 0.1rem solid var(--border-default); }
  .doc > section:first-of-type { border-top: none; }
  .doc h1 { font-size: 3.2rem; margin: 0 0 var(--space-2); }
  .doc h2 { font-size: var(--text-2xl); margin: 0 0 var(--space-2); }
  /* Scoped to section-level headings only — an unscoped .doc h3 outranks .ad-card__title
     and silently misrepresents the component it is supposed to be demonstrating. */
  .doc > section > h3, .do-dont > div > h3 { font-size: var(--text-md); margin: var(--space-6) 0 var(--space-3); color: var(--text-secondary); }
  .doc p.note { color: var(--text-secondary); font-size: var(--text-sm); margin: 0 0 var(--space-4); max-width: 70rem; }
  .demo { display: flex; flex-wrap: wrap; align-items: center; gap: var(--space-3); padding: var(--space-4); border: 0.1rem solid var(--border-default); border-radius: var(--radius-lg); background: var(--surface-page); }
  .demo--stack { flex-direction: column; align-items: stretch; }
  .demo--muted { background: var(--surface-subtle); }
  .sw-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(15rem, 1fr)); gap: var(--space-2); }
  .sw { margin: 0; }
  .sw__chip { height: 6.4rem; border-radius: var(--radius-md); border: 0.1rem solid var(--border-default); display: flex; align-items: flex-end; padding: var(--space-2); font-size: 1.1rem; font-family: monospace; color: var(--text-primary); }
  .sw__chip--dark { color: var(--text-inverse); }
  .sw figcaption { margin-top: var(--space-1); display: flex; flex-direction: column; gap: 0.2rem; }
  .sw code { font-size: 1.1rem; color: var(--text-primary); }
  .sw span { font-size: 1.1rem; color: var(--text-tertiary); }
  .row { display: flex; align-items: baseline; gap: var(--space-4); padding-block: var(--space-2); border-bottom: 0.1rem solid var(--border-default); }
  .row:last-child { border-bottom: none; }
  .row code { width: 14rem; flex: none; font-size: 1.2rem; color: var(--text-secondary); }
  .bar { height: 1.6rem; background: var(--color-primary); border-radius: var(--radius-sm); }
  .radius-box { width: 9rem; height: 6rem; background: var(--surface-muted); border: 0.1rem solid var(--border-default); }
  .shadow-box { width: 12rem; height: 7rem; background: var(--surface-page); border-radius: var(--radius-lg); margin: var(--space-2); }
  .icon-tile { display: flex; flex-direction: column; align-items: center; gap: var(--space-1); width: 9rem; }
  .icon-tile img { width: 2.4rem; height: 2.4rem; }
  .icon-tile span { font-size: 1rem; color: var(--text-tertiary); text-align: center; }
  .do-dont { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: var(--space-4); }
  .do-dont ul { display: flex; flex-direction: column; gap: var(--space-2); font-size: var(--text-sm); }
  .do-dont li { padding-inline-start: var(--space-4); position: relative; color: var(--text-secondary); }
  .do-dont li::before { position: absolute; inset-inline-start: 0; top: 0.4rem; width: 1.4rem; height: 1.4rem; content: ''; }
  .do li::before { background: var(--color-success); mask: url('icons/status/check-circle.svg') center / contain no-repeat; -webkit-mask: url('icons/status/check-circle.svg') center / contain no-repeat; }
  .dont li::before { background: var(--color-error); mask: url('icons/action/close.svg') center / contain no-repeat; -webkit-mask: url('icons/action/close.svg') center / contain no-repeat; }
  .frame { width: 100%; height: 46rem; border: 0.1rem solid var(--border-default); border-radius: var(--radius-lg); background: var(--surface-page); }
  .frame--tall { height: 60rem; }
  .frame-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(34rem, 1fr)); gap: var(--space-4); }
  .frame-label { font-size: var(--text-sm); font-weight: var(--weight-semibold); margin-bottom: var(--space-2); }
  @media (max-width: 950px) {
    .shell { grid-template-columns: minmax(0, 1fr); }
    .nav { position: static; height: auto; }
    .do-dont { grid-template-columns: minmax(0, 1fr); }
  }
</style>
</head>
<body>

<div class="shell">
  <nav class="nav">
    <div class="nav__brand"><img src="icons/brand/logo-with-text.svg" alt="dubizzle"></div>
    <a href="#overview">Overview</a>
    <hr>
    <a href="#colors">Colors</a>
    <a href="#typography">Typography</a>
    <a href="#spacing">Spacing</a>
    <a href="#radii">Radii &amp; shadows</a>
    <a href="#layout">Layout &amp; grid</a>
    <a href="#icons">Icons</a>
    <hr>
    <a href="#buttons">Buttons</a>
    <a href="#forms">Form controls</a>
    <a href="#tags">Chips &amp; pills</a>
    <a href="#cards">Ad cards</a>
    <a href="#nav-components">Tabs &amp; pagination</a>
    <hr>
    <a href="#chrome">Header &amp; footer</a>
    <a href="#templates">Page templates</a>
    <a href="#rules">Rules</a>
  </nav>

  <main class="doc">

    <section id="overview">
      <h1>dubizzle Egypt Design System</h1>
      <p class="note">
        Extracted from the production <code>dubizzle-maple</code> monorepo — ${tokens.tokenCount.toLocaleString()} tokens,
        ${icons.total} icons, and 23 page templates. Red-primary on white, dense and utilitarian.
        Everything on this page is rendered from the same stylesheets the templates use.
      </p>
      <div class="demo">
        <a class="btn btn--primary" href="templates/index.html">Browse page templates</a>
        <a class="btn btn--secondary" href="icons/index.html">Browse all ${icons.total} icons</a>
        <a class="btn btn--ghost" href="tokens/tokens.css">View tokens.css</a>
      </div>
    </section>

    <section id="colors">
      <h2>Colors</h2>
      <p class="note">
        Red is action and brand — never decoration. The UI is white and light gray with red accents.
        Use the semantic aliases in your work; the raw scales exist so the aliases have somewhere to point.
      </p>
      <h3>Semantic aliases — use these</h3>
      <div class="sw-grid">
${swatchGrid(SEMANTIC_COLORS)}
      </div>
${colorSections}
    </section>

    <section id="typography">
      <h2>Typography</h2>
      <p class="note">Proxima Nova for Latin, GESS for Arabic. Base unit is 1rem = 10px.</p>
      <h3>Size scale</h3>
      <div class="demo demo--stack">
${TYPE_SIZES.map(
  (name) => `        <div class="row">
          <code>${name} · ${tokens.groups['font-size']?.[name] ?? literal(name)}</code>
          <span style="font-size:var(${name});font-weight:600">Post your ad in minutes</span>
        </div>`,
).join('\n')}
      </div>
      <h3>Weights</h3>
      <div class="demo demo--stack">
${WEIGHTS.map(
  ([name, label]) => `        <div class="row">
          <code>${name}</code>
          <span style="font-size:1.8rem;font-weight:var(${name})">${label} — Apartment for sale in Zamalek</span>
        </div>`,
).join('\n')}
      </div>
      <h3>Arabic (GESS)</h3>
      <div class="demo">
        <span style="font-family:var(--font-arabic);font-size:2.4rem;font-weight:700">استكشف أكبر سوق في مصر</span>
      </div>
    </section>

    <section id="spacing">
      <h2>Spacing</h2>
      <p class="note">4px base unit. <code>--space-4</code> (16px) is the default. There is no 13px and no 18px.</p>
      <div class="demo demo--stack">
${SPACES.map(
  (name) => `        <div class="row">
          <code>${name} · ${resolvedSpacing(name)}</code>
          <span class="bar" style="width:var(${name})"></span>
        </div>`,
).join('\n')}
      </div>
    </section>

    <section id="radii">
      <h2>Radii &amp; shadows</h2>
      <p class="note">
        Nothing is more rounded than 1.2rem except pills and avatars. All four shadows are
        near-invisible by design — never author a new one.
      </p>
      <h3>Border radius</h3>
      <div class="demo">
${RADII.map(
  ([name, note]) => `        <figure class="sw" style="width:9rem">
          <div class="radius-box" style="border-radius:var(${name})"></div>
          <figcaption><code>${name}</code><span>${note}</span></figcaption>
        </figure>`,
).join('\n')}
      </div>
      <h3>Shadows</h3>
      <div class="demo demo--muted">
${SHADOWS.map(
  ([name, note]) => `        <figure class="sw" style="width:13rem">
          <div class="shadow-box" style="box-shadow:var(${name})"></div>
          <figcaption><code>${name}</code><span>${note}</span></figcaption>
        </figure>`,
).join('\n')}
      </div>
    </section>

    <section id="layout">
      <h2>Layout &amp; grid</h2>
      <p class="note">Extracted from the facelift stylesheets. 768px is the real mobile/desktop split.</p>
      <div class="demo demo--stack">
        <div class="row"><code>Page width</code><span>1280px max, 2.4rem gutters</span></div>
        <div class="row"><code>Search layout</code><span>30.4rem filter rail + fluid results, 1.6rem gap</span></div>
        <div class="row"><code>Results grid</code><span>1 column → 2 at 768px → 3 at 1280px, 1.2rem gap</span></div>
        <div class="row"><code>Ad detail</code><span>content column + 34rem seller rail</span></div>
        <div class="row"><code>Header</code><span>5.9rem with verticals, sticky, z-index 6</span></div>
        <div class="row"><code>Breakpoints</code><span>360 · 480 · <strong>768</strong> · 950 · 1280</span></div>
      </div>
    </section>

    <section id="icons">
      <h2>Icons</h2>
      <p class="note">
        ${icons.total} icons in ${Object.keys(icons.categories).length} categories, all from production.
        Never use emoji, never pull in Lucide or Font Awesome. <!-- ds-ignore -->
      </p>
      <div class="demo">
${sampleIcons
  .map(
    (icon) => `        <div class="icon-tile">
          <img src="icons/${icon.category}/${icon.name}.${icon.path.split('.').pop()}" alt="" loading="lazy">
          <span>${icon.name}</span>
        </div>`,
  )
  .join('\n')}
      </div>
      <p class="note" style="margin-top:1.6rem"><a class="btn btn--secondary" href="icons/index.html">See all ${icons.total} icons</a></p>
    </section>

    <section id="buttons">
      <h2>Buttons</h2>
      <p class="note">Four variants, three sizes. One primary per view — it's the main action.</p>
      <h3>Variants</h3>
      <div class="demo">
        <button class="btn btn--primary">Post Your Ad</button>
        <button class="btn btn--secondary">Cancel</button>
        <button class="btn btn--tertiary">Skip for now</button>
        <button class="btn btn--ghost">View more</button>
      </div>
      <h3>Sizes</h3>
      <div class="demo">
        <button class="btn btn--primary btn--sm">Small</button>
        <button class="btn btn--primary">Default</button>
        <button class="btn btn--primary btn--lg">Large</button>
      </div>
      <h3>Disabled</h3>
      <div class="demo">
        <button class="btn btn--primary" disabled>Primary</button>
        <button class="btn btn--secondary" disabled>Secondary</button>
      </div>
      <h3>Contact CTAs</h3>
      <p class="note">Fixed tints — Chat red, Call blue, WhatsApp green. Don't restyle them.</p>
      <div class="demo">
        <button class="contact-btn contact-btn--chat"><img src="icons/action/chat.svg" alt=""> Chat</button>
        <button class="contact-btn contact-btn--call"><img src="icons/action/call.svg" alt=""> Call</button>
        <button class="contact-btn contact-btn--whatsapp"><img src="icons/social/whatsapp.svg" alt=""> WhatsApp</button>
      </div>
    </section>

    <section id="forms">
      <h2>Form controls</h2>
      <div class="demo demo--stack" style="max-width:46rem">
        <div class="field">
          <label class="field__label" for="p-name">Ad title</label>
          <input class="input" id="p-name" type="text" placeholder="e.g. Apartment for sale in Zamalek 200m">
          <span class="field__hint">Include the area, size and finishing.</span>
        </div>
        <div class="field">
          <label class="field__label" for="p-city">City</label>
          <select class="select" id="p-city">
            <option>Cairo</option>
            <option>Giza</option>
            <option>Alexandria</option>
          </select>
        </div>
        <div class="field">
          <label class="field__label" for="p-desc">Description</label>
          <textarea class="textarea" id="p-desc" placeholder="Describe the property."></textarea>
        </div>
        <div class="field">
          <label class="field__label" for="p-err">Phone number</label>
          <input class="input" id="p-err" type="text" value="012" style="border-color:var(--color-error)">
          <span class="field__error">Enter a valid Egyptian phone number</span>
        </div>
      </div>
      <h3>Selection controls</h3>
      <div class="demo">
        <label class="control"><input type="checkbox" checked><span class="control__box"><svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M2 7l3.5 3.5L12 4" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></span> Checked</label>
        <label class="control"><input type="checkbox"><span class="control__box"><svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M2 7l3.5 3.5L12 4" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></span> Unchecked</label>
        <label class="control"><input type="radio" name="demo" checked><span class="control__radio"></span> Selected</label>
        <label class="control"><input type="radio" name="demo"><span class="control__radio"></span> Unselected</label>
        <label class="control"><input type="checkbox" checked><span class="control__track"></span> Toggle on</label>
        <label class="control"><input type="checkbox"><span class="control__track"></span> Toggle off</label>
      </div>
    </section>

    <section id="tags">
      <h2>Chips &amp; pills</h2>
      <p class="note">Chips are interactive filters. Pills are read-only status.</p>
      <h3>Filter chips</h3>
      <div class="demo">
        <span class="chip chip--active">New Cairo</span>
        <span class="chip">Maadi</span>
        <span class="chip">Zamalek</span>
        <span class="chip">6th of October</span>
      </div>
      <h3>Status pills</h3>
      <div class="demo">
        <span class="pill pill--regular">Regular</span>
        <span class="pill pill--success">Live</span>
        <span class="pill pill--featured">Featured</span>
        <span class="pill pill--error">Expired</span>
        <span class="pill pill--boosted">Boosted</span>
      </div>
    </section>

    <section id="cards">
      <h2>Ad cards</h2>
      <p class="note">
        The hierarchy is price → title → specs → location/time, and it must stay that way.
        Featured and Elite are overlay badges on the image, not pills in the body.
      </p>
      <div class="demo demo--muted">
        <div style="width:28rem">
          <article class="ad-card">
            <div class="ad-card__media media-placeholder">
              <span class="ad-card__badge ad-card__badge--featured">Featured</span>
              <button class="ad-card__fav" aria-label="Save"><img src="icons/action/heart.svg" alt=""></button>
              <span class="ad-card__photos"><img src="icons/media/image-count.svg" alt=""> 12</span>
            </div>
            <div class="ad-card__body">
              <p class="ad-card__price">EGP 8,500,000</p>
              <h3 class="ad-card__title">Apartment for sale in Zamalek 200m fully finished</h3>
              <p class="ad-card__specs"><span>3 Beds</span> · <span>2 Baths</span> · <span>200 m²</span></p>
              <p class="ad-card__meta"><img src="icons/location/location-filled.svg" alt=""> Zamalek, Cairo</p>
              <p class="ad-card__time">2 hours ago</p>
            </div>
          </article>
        </div>
        <div style="width:28rem">
          <article class="ad-card">
            <div class="ad-card__media media-placeholder">
              <span class="ad-card__badge ad-card__badge--elite">Elite</span>
              <button class="ad-card__fav" aria-label="Save"><img src="icons/action/heart.svg" alt=""></button>
              <span class="ad-card__photos"><img src="icons/media/image-count.svg" alt=""> 28</span>
            </div>
            <div class="ad-card__body">
              <p class="ad-card__price">EGP 32,000,000</p>
              <h3 class="ad-card__title">Villa for sale Mivida compound - prime location</h3>
              <p class="ad-card__specs"><span>5 Beds</span> · <span>4 Baths</span> · <span>420 m²</span></p>
              <p class="ad-card__meta"><img src="icons/location/location-filled.svg" alt=""> Mivida, New Cairo</p>
              <p class="ad-card__time">1 day ago</p>
            </div>
          </article>
        </div>
      </div>
      <h3>List variant — three category components</h3>
      <p class="note">
        The list card shares one shell (<code>.ad-list-card</code>) but the body differs by
        vertical. <strong>Cars</strong>: price + model chip, a title, then a year · km ·
        transmission · fuel spec line. <strong>Property</strong>: no free-text title — the body
        leads with the property type and beds · baths · area, then attribute chips.
        <strong>Goods</strong>: price, title, a single condition attribute — no structured specs.
        All three keep the price charcoal and the contact CTAs at the bottom.
      </p>
      <div class="demo demo--muted demo--stack">

        <!-- Cars -->
        <article class="ad-list-card">
          <div class="ad-list-card__media media-placeholder media-placeholder--sm"></div>
          <div class="ad-list-card__body">
            <div class="ad-list-card__head">
              <p class="ad-card__price">EGP 2,850,000</p>
              <span class="chip">E200</span>
            </div>
            <h3 class="ad-card__title">Mercedes-Benz E200 2021 - full options</h3>
            <p class="ad-card__specs"><span>2021</span> · <span>45,000 km</span> · <span>Automatic</span> · <span>Benzine</span></p>
            <p class="ad-card__meta"><img src="icons/location/location-filled.svg" alt=""> Sheikh Zayed, Giza</p>
            <div class="ad-list-card__actions">
              <button class="contact-btn contact-btn--call"><img src="icons/action/call.svg" alt=""> Call</button>
              <button class="contact-btn contact-btn--whatsapp"><img src="icons/social/whatsapp.svg" alt=""> WhatsApp</button>
            </div>
          </div>
        </article>

        <!-- Property -->
        <article class="ad-list-card">
          <div class="ad-list-card__media media-placeholder media-placeholder--sm"></div>
          <div class="ad-list-card__body">
            <p class="ad-card__price">EGP 5,150,000</p>
            <p class="ad-card__specs"><strong>Apartment</strong> · <span>3 Beds</span> · <span>2 Baths</span> · <span>150 m²</span></p>
            <div class="attr-chips">
              <span class="attr-chip">Completion Status <strong>Ready</strong></span>
              <span class="attr-chip">Ownership <strong>Primary</strong></span>
            </div>
            <div class="ad-list-card__footer">
              <span><img src="icons/location/location-filled.svg" alt="" width="16" height="16"> New Cairo, Cairo</span>
              <span>2 hours ago</span>
            </div>
            <div class="ad-list-card__actions">
              <button class="contact-btn contact-btn--call"><img src="icons/action/call.svg" alt=""> Call</button>
              <button class="contact-btn contact-btn--whatsapp"><img src="icons/social/whatsapp.svg" alt=""> WhatsApp</button>
            </div>
          </div>
        </article>

        <!-- Goods -->
        <article class="ad-list-card">
          <div class="ad-list-card__media media-placeholder media-placeholder--sm"></div>
          <div class="ad-list-card__body">
            <p class="ad-card__price">EGP 62,000</p>
            <h3 class="ad-card__title">iPhone 15 Pro Max 256GB - Natural Titanium</h3>
            <div class="attr-chips">
              <span class="attr-chip">Condition <strong>Used</strong></span>
            </div>
            <div class="ad-list-card__footer">
              <span><img src="icons/location/location-filled.svg" alt="" width="16" height="16"> Nasr City, Cairo</span>
              <span>35 minutes ago</span>
            </div>
            <div class="ad-list-card__actions">
              <button class="contact-btn contact-btn--call"><img src="icons/action/call.svg" alt=""> Call</button>
              <button class="contact-btn contact-btn--chat"><img src="icons/action/chat.svg" alt=""> Chat</button>
            </div>
          </div>
        </article>

      </div>
    </section>

    <section id="nav-components">
      <h2>Tabs &amp; pagination</h2>
      <div class="demo demo--stack">
        <div class="tabs">
          <button class="tabs__tab tabs__tab--active">Active (6)</button>
          <button class="tabs__tab">Pending (1)</button>
          <button class="tabs__tab">Expired (3)</button>
          <button class="tabs__tab">Drafts (2)</button>
        </div>
      </div>
      <h3>Pagination</h3>
      <div class="demo">
        <div class="pagination">
          <button class="pagination__btn" disabled>‹</button>
          <button class="pagination__btn pagination__btn--active">1</button>
          <button class="pagination__btn">2</button>
          <button class="pagination__btn">3</button>
          <button class="pagination__btn">4</button>
          <span class="pagination__btn">…</span>
          <button class="pagination__btn">12</button>
          <button class="pagination__btn">›</button>
        </div>
      </div>
    </section>

    <section id="chrome">
      <h2>Header &amp; footer</h2>
      <p class="note">
        Recreated from the live dubizzle.com.eg markup. Note the search submit is charcoal,
        not red — red is reserved for Post Your Ad.
      </p>
      <div class="frame-grid">
        <div>
          <p class="frame-label">Desktop header + footer</p>
          <iframe class="frame" src="templates/desktop/home.html" title="Desktop home" loading="lazy"></iframe>
        </div>
        <div>
          <p class="frame-label">Mobile header + bottom nav</p>
          <iframe class="frame" src="templates/mobile/home.html" title="Mobile home" loading="lazy"></iframe>
        </div>
      </div>
    </section>

    <section id="templates">
      <h2>Page templates</h2>
      <p class="note">
        23 templates across 12 page types, desktop and mobile. Copy one and swap the content —
        never start from a blank page.
      </p>
      <div class="frame-grid">
        <div>
          <p class="frame-label">Search results — desktop</p>
          <iframe class="frame frame--tall" src="templates/desktop/search.html" title="Search results" loading="lazy"></iframe>
        </div>
        <div>
          <p class="frame-label">Ad detail — desktop</p>
          <iframe class="frame frame--tall" src="templates/desktop/ad-detail.html" title="Ad detail" loading="lazy"></iframe>
        </div>
      </div>
      <p class="note" style="margin-top:1.6rem"><a class="btn btn--primary" href="templates/index.html">Open the full template gallery</a></p>
    </section>

    <section id="rules">
      <h2>Rules</h2>
      <p class="note">
        The full set is in <code>RULES.md</code>, enforced by <code>npm run check:design</code>.
        These are the ones that most often get broken.
      </p>
      <div class="do-dont">
        <div class="demo demo--stack do">
          <h3 style="margin-top:0">Do</h3>
          <ul>
            <li>Use tokens for every colour, space, radius and shadow</li>
            <li>Use icons from this set — all ${icons.total} of them</li>
            <li>Write real EGP prices and real Egyptian place names</li>
            <li>Keep the ad-card hierarchy: price, title, specs, meta</li>
            <li>Choose the denser layout when torn</li>
            <li>Use logical properties so RTL flips correctly</li>
          </ul>
        </div>
        <div class="demo demo--stack dont">
          <h3 style="margin-top:0">Don't</h3>
          <ul>
            <li>Gradients — only the Featured, Elite and Pro badges</li>
            <li>Emoji as icons, or Lucide / Font Awesome / Google Fonts</li> <!-- ds-ignore -->
            <li>Glassmorphism, blur, or coloured glows</li>
            <li>Scale or bounce on hover — colour transitions only</li>
            <li>Purple, indigo, teal — they appear nowhere in the brand</li>
            <li>Centred marketing heroes or three evenly-weighted cards</li>
            <li>Radius above 1.2rem, or a hand-authored shadow</li>
          </ul>
        </div>
      </div>
    </section>

  </main>
</div>

</body>
</html>
`;

writeFileSync(join(ROOT, 'design-kit/index.html'), page);
console.log(`Built design-kit/index.html — ${tokens.tokenCount} tokens, ${icons.total} icons referenced`);
