#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { collectVariables, resolveAll, resolveValue, toKebab } from './lib/parse-variables.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const config = JSON.parse(readFileSync(join(ROOT, 'design-sync.config.json'), 'utf8'));

const monorepo = process.argv[2] || config.monorepoPath;
if (!existsSync(monorepo)) {
  console.error(`Monorepo not found: ${monorepo}`);
  console.error('Pass a path: npm run sync:tokens -- "/path/to/dubizzle-maple-master"');
  process.exit(1);
}

const packageRoots = config.packageRoots.map((p) => join(monorepo, p));
const entry = join(monorepo, config.entryVariables);

const raw = collectVariables(entry, packageRoots);
const resolved = resolveAll(raw);

// Breakpoints live in their own file, outside the variables import chain.
const breakpointFile = join(monorepo, 'frontend/horizontal/horizontal/styles/deviceWidths.css');
if (existsSync(breakpointFile)) {
  for (const [key, value] of collectVariables(breakpointFile, packageRoots)) {
    resolved.set(key, resolveValue(value, raw));
  }
}

const COLOR_VALUE = /^(#[0-9a-f]{3,8}|rgba?\(|hsla?\(|white$|black$|transparent$|linear-gradient|radial-gradient)/i;

/**
 * PostCSS evaluated bare arithmetic at build time (`$containerMargin: 2 * $largeSpacing`),
 * but CSS custom properties don't — an unwrapped expression silently breaks the consumer.
 * Wrap anything that is purely numbers, units and operators.
 */
function normalizeArithmetic(value) {
  if (value.startsWith('calc(')) return value;
  const hasOperator = /\s[*/+]\s/.test(value);
  const isPureMath =
    value.replace(/-?[\d.]+(rem|px|em|%|vh|vw|ms|s)?/g, '').replace(/[\s()+*/-]/g, '') === '';
  return hasOperator && isPureMath ? `calc(${value})` : value;
}

function classify(name, value) {
  if (/^deviceWidth/.test(name)) return 'breakpoint';
  if (/shadow/i.test(name)) return 'shadow';
  if (/fontWeight/i.test(name)) return 'font-weight';
  if (/fontSize|FontSize/.test(name)) return 'font-size';
  if (/^font|fontFamily/i.test(name)) return 'font-family';
  if (/lineHeight|letterSpacing/i.test(name)) return 'typography';
  if (/radius/i.test(name)) return 'radius';
  if (COLOR_VALUE.test(value)) return 'color';
  if (/spacing|padding|margin|gap/i.test(name)) return 'spacing';
  if (/width|height|size/i.test(name)) return 'size';
  if (/zindex|z-index/i.test(name)) return 'z-index';
  return 'other';
}

const groups = new Map();
/* A handful of tokens are url() references to bitmaps that live in the monorepo's
   asset folders. Emitting them would make every bundler try (and fail) to resolve a
   path we don't ship, so they're recorded in tokens.json instead of the stylesheet. */
const assetRefs = {};

for (const [name, rawValue] of [...resolved].sort(([a], [b]) => a.localeCompare(b))) {
  const value = normalizeArithmetic(rawValue);
  const cssName = `--${toKebab(name)}`;
  if (/\burl\(/.test(value)) {
    assetRefs[cssName] = value;
    continue;
  }
  const kind = classify(name, value);
  if (!groups.has(kind)) groups.set(kind, []);
  groups.get(kind).push({ name, cssName, value, kind });
}

const ORDER = [
  'color',
  'font-family',
  'font-size',
  'font-weight',
  'typography',
  'spacing',
  'radius',
  'shadow',
  'size',
  'breakpoint',
  'z-index',
  'other',
];

const outDir = join(ROOT, 'design-kit/tokens');
mkdirSync(outDir, { recursive: true });

// ── tokens.css — every production token, resolved, grouped ─────────────────
let css = `/* GENERATED by scripts/sync-tokens.mjs — do not edit by hand.
   Source: ${config.brand} variables chain (strat -> horizontal -> dubizzle-facelift -> dubizzle-eg)
   Regenerate with: npm run sync:tokens
   ${resolved.size} tokens resolved. */

:root {
`;
for (const kind of ORDER) {
  const entries = groups.get(kind);
  if (!entries?.length) continue;
  css += `\n  /* ── ${kind} (${entries.length}) ── */\n`;
  for (const { cssName, value } of entries) {
    css += `  ${cssName}: ${value};\n`;
  }
}
/* ── Semantic API ──────────────────────────────────────────────────────────
   The 1,269 production tokens above are faithful but verbose, and their names
   churn with the codebase. Everything downstream (components, templates, the
   design linter) targets this small stable vocabulary instead, mapped onto the
   production tokens here. When upstream renames something, this map is the only
   place that needs to change. */
const SEMANTIC = {
  color: {
    '--color-primary': 'var(--primary-color)',
    '--color-primary-hover': 'var(--primary-button-hover-color)',
    '--color-primary-active': 'var(--primary-button-active-color)',
    '--color-primary-light': 'var(--red-01)',
    '--color-primary-muted': 'var(--red-02)',
    '--color-accent': 'var(--accent-color)',
    '--color-secondary': 'var(--secondary-color)',
    '--color-secondary-light': 'var(--blue-02)',
    '--color-success': 'var(--green-05)',
    '--color-success-bg': 'var(--green-02)',
    '--color-warning': 'var(--yellow-05)',
    '--color-warning-bg': 'var(--yellow-02)',
    '--color-error': 'var(--error-color)',
    '--color-error-bg': 'var(--red-02)',
    '--color-info': 'var(--blue-05)',
    '--color-info-bg': 'var(--blue-02)',
    '--text-primary': 'var(--text-color)',
    '--text-secondary': 'var(--label-color)',
    '--text-tertiary': 'var(--gray-04)',
    '--text-inverse': 'var(--white, #ffffff)',
    '--surface-page': '#ffffff',
    '--surface-subtle': 'var(--gray-00)',
    '--surface-muted': 'var(--gray-01)',
    '--surface-card': '#ffffff',
    '--border-default': 'var(--border-color)',
    '--border-strong': 'var(--gray-03)',
    '--border-input': 'var(--input-color)',
    '--border-focus': 'var(--active-input-border-color)',
    '--border-subtle': 'rgba(0, 47, 52, 0.2)',
    // Translucent overlays for controls/scrims sitting on top of media (a card
    // photo). No opaque token can stand in — the alpha is the point.
    '--overlay-light': 'rgba(255, 255, 255, 0.9)',
    '--overlay-dark': 'rgba(35, 38, 42, 0.75)',
    '--featured-accent': 'var(--featured-ad-accent-color)',
    // Badge gradients as production renders them (docs/LIVE-MEASUREMENTS.md) — the monorepo's
    // --featured-ad-accent-bgcolor / --elite-tag-bg are angled variants that no longer ship.
    '--featured-gradient': 'linear-gradient(90deg, var(--blue-08), var(--blue-09))',
    '--elite-gradient': 'linear-gradient(90deg, var(--yellow-03), var(--yellow-06))',
    // Bottom fade behind a card photo's slider dots.
    '--overlay-image-fade': 'linear-gradient(transparent, rgba(0, 0, 0, 0.4))',
    // Mobile app-promo surfaces (docs/LIVE-MEASUREMENTS.md).
    '--app-promo-gradient': 'linear-gradient(270deg, #ffedea -0.93%, #fefbf5 50.98%)',
    '--app-icon-gradient': 'linear-gradient(#ffffff, #ffedea)',
    '--pro-gradient': 'var(--pro-badge-background)',
    // Ad-detail gallery furniture, measured on the live mobile DPV
    // (docs/LIVE-MEASUREMENTS.md): the photo counter's scrim, the next-photo
    // arrow's disc, and the idle slider dot.
    '--overlay-counter': 'rgba(0, 0, 0, 0.75)',
    '--overlay-arrow': 'rgba(0, 0, 0, 0.2)',
    '--dot-idle': 'rgba(255, 255, 255, 0.4)',
    // "Car / Property of the Week" ribbon.
    '--week-gradient': 'linear-gradient(92.05deg, #e00000 64.95%, #ba0000 121.09%)',

    // ── Gradients that are structure, not decoration ──────────────────────────
    // Measured across 124 live captures (scripts/.tmp-find-effects.mjs pattern):
    // 333 rendered gradients, every one doing a job. See docs/DECISIONS.md.

    // The "Post your ad" CTA band under a results grid. One component, tinted per
    // vertical. The 79.97% stop is production's own value, not a rounded 80%.
    '--cta-band-home': 'linear-gradient(#f7fafe 0, #e7f1fd 79.97%)',
    '--cta-band-motors': 'linear-gradient(#e9eaf7 0, #e9eaf7 79.97%)',
    '--cta-band-property': 'linear-gradient(270deg, #fef3de 0, #ffe1e1 79.97%)',
    '--cta-band-mobiles': 'linear-gradient(#e7f1fd 0, #e7f1fd 79.97%)',
    // Horizontal rails (brand strips, "more from this seller") fade their overflow
    // edge instead of clipping it. Mirrored for the other end / RTL.
    '--rail-fade-end': 'linear-gradient(to right, #f0f0f0 -7.33%, #f0f0f0 25.45%, rgba(255, 255, 255, 0) 73.44%)',
    '--rail-fade-start': 'linear-gradient(to left, #f0f0f0 -7.33%, #f0f0f0 25.45%, rgba(255, 255, 255, 0) 73.44%)',
    // The DPV specs strip: a barely-there vertical shade, not a flat fill.
    '--surface-depth': 'linear-gradient(#f6f6f6, #f0f0f0)',
    // The product's only frosted surface — the media-type chip ("Video") sitting on
    // a card photo, where the image behind it is arbitrary and contrast can't be
    // guaranteed any other way. Pair with --glass-chip-blur.
    '--glass-chip-bg': 'rgba(23, 25, 28, 0.75)',

    // ── Opt-in frosted panel (AUTHORED, NOT MEASURED) ─────────────────────────
    // Everything above this line was measured on live dubizzle. These four were
    // authored on the user's instruction (2026-09-17) so that glassmorphism is
    // available as a deliberate option. Production does not currently render them.
    // If a design ships with one, measure it and move it up. Keep the distinction:
    // D-007 exists because invented values were once presented as facts.
    '--glass-panel-bg': 'rgba(255, 255, 255, 0.72)',
    '--glass-panel-bg-dark': 'rgba(23, 25, 28, 0.64)',
    '--glass-panel-border': 'rgba(255, 255, 255, 0.4)',
  },
  /* ── Motion ───────────────────────────────────────────────────────────────
     ADOPTED from the dubizzle Egypt design-system export (Credit Info / Protool
     bundle, 2026-09-17), NOT measured by this project. 37 of that bundle's 38
     colour tokens matched our measured palette exactly, which is why its motion
     values are credited — but credited is not measured. Verify against live with
     the `motion-design` skill before treating any of these as production fact,
     and note the keyframes in its motion.css come from a "Sell with AI"
     prototype that appears nowhere in our 142 live captures. See D-013. */
  motion: {
    '--ease-standard': 'cubic-bezier(0.4, 0, 0.2, 1)',
    '--duration-fast': '0.15s',
    '--duration-base': '0.25s',
    '--skeleton-duration': '1.5s',
  },
  typography: {
    '--font-primary': 'var(--font-ltr)',
    '--font-arabic': "GESS, var(--font-ltr)",
    '--text-xs': 'var(--small-font-size)',
    '--text-sm': 'var(--font-size)',
    '--text-md': 'var(--medium-font-size)',
    '--text-lg': 'var(--title-font-size)',
    '--text-xl': '2rem',
    '--text-2xl': 'var(--large-font-size)',
    '--text-3xl': '3.2rem',
    '--weight-thin': 'var(--font-weight-ultra-light)',
    '--weight-light': 'var(--font-weight-light)',
    '--weight-regular': 'var(--font-weight-normal)',
    // Medium has no monorepo variable; production uses 500 for inactive quick-link tabs (motors).
    '--weight-medium': '500',
    '--weight-semibold': 'var(--font-weight-semi-bold)',
    '--weight-bold': 'var(--font-weight-bold)',
    '--weight-black': 'var(--font-weight-ultra-bold)',
    '--leading-tight': 'var(--heading-line-height)',
    '--leading-normal': 'var(--line-height)',
    '--leading-relaxed': '1.6',
    '--tracking-normal': '0',
    '--tracking-wide': 'var(--letter-spacing)',
  },
  spacing: {
    '--space-0': '0',
    '--space-1': '0.4rem',
    '--space-2': 'var(--content-padding)',
    '--space-3': 'var(--common-spacing)',
    '--space-4': 'var(--primary-spacing)',
    '--space-5': '2rem',
    '--space-6': 'var(--large-spacing)',
    '--space-7': '3.2rem',
    '--space-8': 'var(--section-spacing)',
    '--space-9': '4.8rem',
    '--space-10': '6.4rem',
  },
  radius: {
    '--radius-sm': '0.4rem',
    '--radius-md': 'var(--input-border-radius)',
    '--radius-lg': 'var(--ad-card-border-radius)',
    '--radius-xl': '1.2rem',
    // Highlighted list card (Car / Property of the Week slot) only.
    '--radius-2xl': '1.6rem',
    // App icon tile in the mobile app banner only.
    '--radius-app-icon': '1rem',
    '--radius-pill': 'var(--pill-border-radius)',
    '--radius-full': '9999px',
  },
  shadow: {
    '--shadow-card': 'var(--ad-card-shadow)',
    '--shadow-card-hover': 'var(--ad-card-shadow-hover)',
    '--shadow-dropdown': 'var(--dropdown-shadow)',
    '--shadow-header': '0px 2px 4px 0px rgba(0,0,0,0.008)',
    '--shadow-control': 'var(--category-switcher-box-shadow)',
    // Mobile web, measured on dubizzle.com.eg (docs/LIVE-MEASUREMENTS.md)
    '--shadow-tile': '0 2px 8px 0 rgba(0, 0, 0, 0.14)', // vertical tiles in the mobile header
    '--shadow-search': '0 2px 10px 0 rgba(0, 0, 0, 0.1)', // mobile search field and favourites button
    '--shadow-bottom-nav': '0 -2px 4px 0 rgba(0, 0, 0, 0.133)',
    // Agency portal, measured on live 2026-09-21 (design-kit/content/portal-filters.json):
    // every filter menu (checklists, category list, date presets). Darker than the repo's
    // --dropdown-shadow (.1), which live uses only for the VIP range panels.
    '--shadow-menu': '0 4px 10px 0 rgba(0, 0, 0, 0.16)',
    // The ad details drawer (repo sideDialog.cssm .large) — a wide soft cast to the left.
    '--shadow-side-panel': '-80px -120px 240px 0 rgba(0, 0, 0, 0.1)',
    // Toast (repo dubizzle-facelift/components/styles/toast.cssm; not yet live-verified).
    '--shadow-toast': '0 3px 8px 0 rgba(0, 0, 0, 0.15)',
    // Header overlays — the location dropdown and the search suggestions both use this pair.
    // The blur half of the media chip (--glass-chip-bg). The only backdrop-filter
    // in the product.
    '--glass-chip-blur': 'blur(4px)',
    // Opt-in panel blur (authored, not measured — see --glass-panel-bg).
    '--glass-panel-blur': 'blur(12px)',
    '--shadow-overlay': '0 0 6px 0 rgba(0, 0, 0, 0.12), 0 6px 6px 0 rgba(0, 0, 0, 0.24)',
    // The signed-in account menu sits on a softer one.
    '--shadow-menu': '0 4px 10px 0 rgba(0, 0, 0, 0.1)',
    // Breadcrumb links: charcoal at 64%, as live draws them.
    '--text-muted': 'rgba(35, 38, 42, 0.64)',
    '--shadow-sticky-header': '0 2px 4px 0 rgba(0, 0, 0, 0.133)', // listing-page header
    '--shadow-floating': '0 4px 12px 0 rgba(0, 0, 0, 0.22)', // Sort / Save bar
  },
  layout: {
    '--page-width': 'var(--page-desktop-width)',
    '--container-gutter': 'var(--large-spacing)',
    '--bp-tiny': 'var(--device-width-tiny-mobile)',
    '--bp-small': 'var(--device-width-small-mobile)',
    '--bp-mobile': 'var(--device-width-mobile)',
    '--bp-tablet': 'var(--device-width-tablet)',
    '--bp-desktop': 'var(--device-width-desktop)',
  },
};

// Fail loudly if an upstream rename broke a mapping, rather than emitting dead vars.
const emitted = new Set([...groups.values()].flat().map((t) => t.cssName));
const missing = [];
for (const group of Object.values(SEMANTIC)) {
  for (const [alias, expression] of Object.entries(group)) {
    for (const [whole, ref] of expression.matchAll(/var\((--[a-z0-9-]+)(\s*,[^)]*)?\)/g)) {
      const hasFallback = whole.includes(',');
      if (!emitted.has(ref) && !hasFallback) missing.push(`${alias} -> ${ref}`);
    }
  }
}

css += `\n  /* ══ SEMANTIC API — target these, not the production tokens above ══ */\n`;
for (const [groupName, entries] of Object.entries(SEMANTIC)) {
  css += `\n  /* ── ${groupName} ── */\n`;
  for (const [alias, expression] of Object.entries(entries)) {
    css += `  ${alias}: ${expression};\n`;
  }
}

css += '}\n';
/* Kit pages and templates link tokens.css and nothing else, so the kit's copy pulls in the
   web fonts — without them the kit renders in the system fallback, ~3px wider per word than
   Storybook (which is how npm run check:parity found this). The library gets its faces from
   src/tokens/index.css instead, so its copy stays token-only. */
const FONT_IMPORT = `/* Web fonts — see design-kit/tokens/fonts.css */\n@import url('./fonts.css');\n\n`;
writeFileSync(join(outDir, 'tokens.css'), css.replace(':root {', `${FONT_IMPORT}:root {`));

/* The React library and the static design kit must never disagree about what a token
   means, so both read the same generated file rather than keeping parallel copies. */
const libTokens = join(ROOT, 'src/tokens/generated.css');
mkdirSync(dirname(libTokens), { recursive: true });
writeFileSync(libTokens, css);

if (missing.length) {
  console.warn(`\n⚠️  ${missing.length} semantic alias(es) point at tokens that no longer exist upstream:`);
  for (const m of missing) console.warn(`     ${m}`);
  console.warn('     Update the SEMANTIC map in scripts/sync-tokens.mjs.');
}


// ── tokens.json — machine readable, for tooling and the design linter ──────
const json = {
  generatedFrom: config.brand,
  tokenCount: resolved.size,
  assetRefs,
  _assetRefsNote:
    'url() tokens pointing at monorepo bitmaps that this package does not ship. Copy the asset and re-point the url if you need one.',
  groups: Object.fromEntries(
    ORDER.filter((k) => groups.has(k)).map((kind) => [
      kind,
      Object.fromEntries(groups.get(kind).map((t) => [t.cssName, t.value])),
    ]),
  ),
};

/* The semantic layer is what everything downstream actually targets, so it belongs in
   the machine-readable output too — not just the stylesheet. Merged into the matching
   groups so consumers can look a token up by name without knowing which layer it came
   from. */
const SEMANTIC_GROUP_TO_KIND = {
  color: 'color',
  typography: 'font-size',
  spacing: 'spacing',
  radius: 'radius',
  shadow: 'shadow',
  layout: 'size',
};

json.semantic = {};
for (const [groupName, entries] of Object.entries(SEMANTIC)) {
  json.semantic[groupName] = entries;
  const kind = SEMANTIC_GROUP_TO_KIND[groupName];
  if (!kind) continue;
  json.groups[kind] = { ...(json.groups[kind] ?? {}), ...entries };
}
writeFileSync(join(outDir, 'tokens.json'), JSON.stringify(json, null, 2));

// ── Console report ────────────────────────────────────────────────────────
console.log(`Resolved ${resolved.size} tokens from ${config.brand}`);
for (const kind of ORDER) {
  if (groups.has(kind)) console.log(`  ${kind.padEnd(14)} ${groups.get(kind).length}`);
}
console.log(`\nWrote design-kit/tokens/tokens.css and tokens.json`);
