/* GENERATED by scripts/build-component-icons.mjs from design-kit/icons — do not edit. */
import type { SVGProps } from 'react';

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, 'dangerouslySetInnerHTML'> {
  size?: number;
}

/** design-kit/icons/action/heart.svg */
export function HeartIcon({ size = 16, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false" {...props}
      dangerouslySetInnerHTML={{ __html: "<path fill=\"var(--icon-heart-inner-fill, currentColor)\" fill-opacity=\"var(--icon-heart-inner-fill-opacity, 0)\" d=\"M15.711 5a4.26 4.26 0 0 1 3.018 1.258 4.422 4.422 0 0 1 1.27 3.051 4.424 4.424 0 0 1-1.19 3.083v.03l-6.246 6.348a.766.766 0 0 1-.543.23.754.754 0 0 1-.543-.23L5.23 12.392A4.424 4.424 0 0 1 4 9.325c0-1.146.442-2.247 1.23-3.067A4.26 4.26 0 0 1 8.248 5a4.26 4.26 0 0 1 3.018 1.258.994.994 0 0 0 1.428 0A4.26 4.26 0 0 1 15.71 5Z\"/> <path fill=\"var(--icon-heart-fill, currentColor)\" d=\"M20.177 4.88a6.292 6.292 0 0 0-8.162-.64 6.272 6.272 0 0 0-8.163 9.482l6.212 6.221a2.78 2.78 0 0 0 3.901 0l6.212-6.221a6.272 6.272 0 0 0 0-8.842Zm-1.41 7.462-6.212 6.211a.76.76 0 0 1-1.08 0l-6.212-6.242a4.292 4.292 0 0 1 0-6.001 4.271 4.271 0 0 1 6.001 0 1.002 1.002 0 0 0 1.42 0 4.271 4.271 0 0 1 6.002 0 4.29 4.29 0 0 1 .08 6.002v.03Z\"/>" }} />
  );
}

/** design-kit/icons/property/beds.svg */
export function BedsIcon({ size = 16, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 12 12" fill="currentColor" aria-hidden="true" focusable="false" {...props}
      dangerouslySetInnerHTML={{ __html: "<path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M3.20662 1.69603C2.91206 1.69603 2.67328 1.93481 2.67328 2.22936V4.24911H5.5575V1.75961C5.5575 1.73805 5.55896 1.71682 5.56179 1.69603H3.20662ZM6.48653 1.69603C6.48936 1.71682 6.49082 1.73805 6.49082 1.75961V4.24911H9.30056V2.22936C9.30056 1.93481 9.06176 1.69603 8.76723 1.69603H6.48653ZM6.02176 5.18244H6.02416H6.02656H9.42869C9.90729 5.18244 10.2954 5.57046 10.2954 6.0491V8.12188C10.2036 8.09981 10.1079 8.08815 10.0094 8.08815H1.96475C1.86628 8.08815 1.77053 8.09981 1.67882 8.12188V6.0491C1.67882 5.57046 2.06684 5.18244 2.54548 5.18244H6.02176ZM1.73995 2.22936V4.43897C1.15026 4.73456 0.745483 5.34456 0.745483 6.0491V9.30741V9.52748V10.7708C0.745483 11.0285 0.954417 11.2375 1.21215 11.2375C1.46988 11.2375 1.67882 11.0285 1.67882 10.7708V9.52748V9.30741C1.67882 9.14948 1.80683 9.02148 1.96475 9.02148H10.0094C10.1673 9.02148 10.2954 9.14948 10.2954 9.30741V9.52748V10.7708C10.2954 11.0285 10.5043 11.2375 10.762 11.2375C11.0198 11.2375 11.2287 11.0285 11.2287 10.7708V9.52748V9.30741V6.0491C11.2287 5.34443 10.8238 4.73434 10.2339 4.43881V2.22936C10.2339 1.41934 9.57722 0.762695 8.76723 0.762695H3.20662C2.3966 0.762695 1.73995 1.41934 1.73995 2.22936Z\" fill=\"currentColor\" />" }} />
  );
}

/** design-kit/icons/property/baths.svg */
export function BathsIcon({ size = 16, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 12 12" fill="currentColor" aria-hidden="true" focusable="false" {...props}
      dangerouslySetInnerHTML={{ __html: "<path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M5.90969 2.15469C6.20218 1.4148 6.91704 0.928711 7.71262 0.928711C8.78336 0.928711 9.65136 1.79671 9.65136 2.86744V5.23246H10.9542C11.0779 5.23246 11.1966 5.28163 11.2841 5.36914C11.3716 5.45666 11.4208 5.57536 11.4208 5.69913V7.81221C11.4208 8.69848 10.9534 9.47561 10.2516 9.91048L10.6813 10.7191C10.8022 10.9467 10.7157 11.2293 10.4881 11.3502C10.2605 11.4711 9.97796 11.3846 9.85702 11.157L9.37229 10.2447L9.37182 10.2437C9.23602 10.2669 9.09649 10.2789 8.95416 10.2789H3.40429C3.24392 10.2789 3.08712 10.2636 2.93528 10.2343L2.9309 10.2424L2.41874 11.1646C2.29361 11.3899 2.00951 11.4711 1.78419 11.346C1.55888 11.2209 1.47766 10.9368 1.6028 10.7115L2.06306 9.88275C1.38568 9.44308 0.937622 8.67995 0.937622 7.81221V5.69912C0.937622 5.44139 1.14656 5.23245 1.40429 5.23245L8.71802 5.23246V2.86744C8.71802 2.31217 8.26789 1.86204 7.71262 1.86204C7.30006 1.86204 6.92934 2.11412 6.77766 2.49782L6.65644 2.80445C6.87591 3.04502 6.97196 3.38894 6.88143 3.72683L4.9727 3.21539C5.07717 2.82558 5.4007 2.55297 5.77534 2.49455L5.90969 2.15469ZM8.95416 9.34555C9.80096 9.34555 10.4875 8.65908 10.4875 7.81221V6.16579L1.87096 6.16579V7.81221C1.87096 8.65908 2.55745 9.34555 3.40429 9.34555H8.95416Z\" fill=\"currentColor\" />" }} />
  );
}

/** design-kit/icons/property/area.svg */
export function AreaIcon({ size = 16, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 12 12" fill="currentColor" aria-hidden="true" focusable="false" {...props}
      dangerouslySetInnerHTML={{ __html: "<path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M1.44794 2.02858C1.44794 1.43948 1.9255 0.961914 2.51461 0.961914H5.52568C5.76825 0.961914 5.9649 1.15856 5.9649 1.40113V6.44318H10.8014C11.044 6.44318 11.2406 6.63983 11.2406 6.8824V9.70389C11.2406 10.293 10.763 10.7706 10.1739 10.7706H3.14206C2.20642 10.7706 1.44794 10.012 1.44794 9.07644V2.02858ZM2.51461 1.84035C2.41064 1.84035 2.32637 1.92462 2.32637 2.02858V9.07644C2.32637 9.52688 2.69157 9.89212 3.14206 9.89212H5.07808L5.07805 7.36569H4.38654C4.14397 7.36569 3.94733 7.16905 3.94733 6.92648C3.94733 6.68391 4.14397 6.48727 4.38654 6.48727H5.08646V4.81476H4.38654C4.14397 4.81476 3.94733 4.61812 3.94733 4.37555C3.94733 4.13298 4.14397 3.93633 4.38654 3.93633H5.08646V1.84035H2.51461ZM5.95648 7.32164L5.95651 9.89212H10.1739C10.2779 9.89212 10.3622 9.80786 10.3622 9.70389V7.32164H5.95648Z\" fill=\"currentColor\" />" }} />
  );
}

/** design-kit/icons/location/location-filled.svg */
export function LocationIcon({ size = 16, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" aria-hidden="true" focusable="false" {...props}
      dangerouslySetInnerHTML={{ __html: "<path d=\"M7.9974 8.00065C8.36406 8.00065 8.67795 7.8701 8.93906 7.60898C9.20017 7.34787 9.33073 7.03398 9.33073 6.66732C9.33073 6.30065 9.20017 5.98676 8.93906 5.72565C8.67795 5.46454 8.36406 5.33398 7.9974 5.33398C7.63073 5.33398 7.31684 5.46454 7.05573 5.72565C6.79462 5.98676 6.66406 6.30065 6.66406 6.66732C6.66406 7.03398 6.79462 7.34787 7.05573 7.60898C7.31684 7.8701 7.63073 8.00065 7.9974 8.00065ZM7.9974 14.6673C6.20851 13.1451 4.8724 11.7312 3.98906 10.4257C3.10573 9.12009 2.66406 7.91176 2.66406 6.80065C2.66406 5.13398 3.20017 3.80621 4.2724 2.81732C5.34462 1.82843 6.58629 1.33398 7.9974 1.33398C9.40851 1.33398 10.6502 1.82843 11.7224 2.81732C12.7946 3.80621 13.3307 5.13398 13.3307 6.80065C13.3307 7.91176 12.8891 9.12009 12.0057 10.4257C11.1224 11.7312 9.78629 13.1451 7.9974 14.6673Z\" fill=\"currentColor\" />" }} />
  );
}

/** design-kit/icons/location/location.svg */
export function LocationOutlineIcon({ size = 16, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 16 16" fill="currentColor" aria-hidden="true" focusable="false" {...props}
      dangerouslySetInnerHTML={{ __html: "<path fill=\"currentColor\" d=\"M8.002 7.998q.552 0 .942-.39.39-.389.389-.941 0-.554-.39-.942-.39-.39-.942-.39-.553 0-.942.39-.39.39-.39.942 0 .553.39.942.39.39.943.39m0 4.744q1.963-1.825 2.916-3.28t.952-2.653q0-1.763-1.12-2.883T8 2.806t-2.748 1.12-1.12 2.883q0 1.199.953 2.65.952 1.454 2.916 3.284m0 1.894q-2.673-2.299-3.988-4.204T2.7 6.812q0-2.488 1.604-3.963Q5.905 1.373 8 1.373t3.7 1.476 1.603 3.963q0 1.715-1.315 3.62T8 14.636\"/>" }} />
  );
}

/** design-kit/icons/media/image-count.svg */
export function PhotoCountIcon({ size = 16, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 12 12" fill="currentColor" aria-hidden="true" focusable="false" {...props}
      dangerouslySetInnerHTML={{ __html: "<path d=\"M2.5 10.5C2.225 10.5 1.98958 10.4021 1.79375 10.2063C1.59792 10.0104 1.5 9.775 1.5 9.5V2.5C1.5 2.225 1.59792 1.98958 1.79375 1.79375C1.98958 1.59792 2.225 1.5 2.5 1.5H9.5C9.775 1.5 10.0104 1.59792 10.2063 1.79375C10.4021 1.98958 10.5 2.225 10.5 2.5V9.5C10.5 9.775 10.4021 10.0104 10.2063 10.2063C10.0104 10.4021 9.775 10.5 9.5 10.5H2.5ZM2.5 9.5H9.5V2.5H2.5V9.5ZM3 8.5H9L7.125 6L5.625 8L4.5 6.5L3 8.5ZM4.78125 4.78125C4.92708 4.63542 5 4.45833 5 4.25C5 4.04167 4.92708 3.86458 4.78125 3.71875C4.63542 3.57292 4.45833 3.5 4.25 3.5C4.04167 3.5 3.86458 3.57292 3.71875 3.71875C3.57292 3.86458 3.5 4.04167 3.5 4.25C3.5 4.45833 3.57292 4.63542 3.71875 4.78125C3.86458 4.92708 4.04167 5 4.25 5C4.45833 5 4.63542 4.92708 4.78125 4.78125Z\" fill=\"currentColor\"/>" }} />
  );
}

/** design-kit/icons/status/elite.svg */
export function EliteIcon({ size = 16, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 9 13" fill="currentColor" aria-hidden="true" focusable="false" {...props}
      dangerouslySetInnerHTML={{ __html: "<path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M8.39 9.588c-.048-1.205-.432-1.302-.878-2.372-.63-1.72.447-3.19-.75-5.016-.367 2.328-2.098 3.004-3.358 4.496-.984 1.166-1.25 2.669-.774 3.723a2.306 2.306 0 0 1 2.176-1.555 2.306 2.306 0 0 1 1.92 3.575c1.097-.395 1.709-1.697 1.664-2.85z\" fill=\"#e00000\" /> <path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M3.906 5.203c.844-.703 2.148-2.006 2.148-3C6.054.69 5.246 0 5.246 0s.351 1.194-2.397 3.73C.482 5.912.816 7.902.824 8.03c.076 1.223.579 2.641 1.468 3.234a3.575 3.575 0 0 1-.575-1.857c0-.202-.178-2.224 2.188-4.205\" fill=\"#e00000\" /> <path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M6.413 11.17c0 .89-.72 1.612-1.606 1.612A1.608 1.608 0 0 1 3.2 11.17c0-.888.719-1.61 1.607-1.61.885 0 1.606.722 1.606 1.61z\" />" }} />
  );
}

/** design-kit/icons/navigation/chevron-down.svg */
export function ChevronDownIcon({ size = 16, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="3 3 12 12" fill="currentColor" aria-hidden="true" focusable="false" {...props}
      dangerouslySetInnerHTML={{ __html: "<path fill=\"currentColor\" d=\"M12.443 6.223 9 9.658 5.558 6.223 4.5 7.28l4.5 4.5 4.5-4.5-1.057-1.057Z\"/>" }} />
  );
}

/** design-kit/icons/action/filters.svg */
export function FiltersIcon({ size = 16, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false" {...props}
      dangerouslySetInnerHTML={{ __html: "<path d=\"M14.9 9h2V7h4V5h-4V3h-2zm6 4v-2h-10v2zm-14-4v2H3v2h4v2h2V9zm6 12v-2h8v-2h-8v-2h-2v6zM2.9 5v2h10V5zm0 12v2h6v-2z\"/>" }} />
  );
}

/** design-kit/icons/media/image.svg */
export function ImagePlaceholderIcon({ size = 16, ...props }: IconProps) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false" {...props}
      dangerouslySetInnerHTML={{ __html: "<g data-name=\"Layer 2\"> <g data-name=\"image\"> <rect width=\"24\" height=\"24\" opacity=\"0\" /> <path d=\"M18 3H6a3 3 0 0 0-3 3v12a3 3 0 0 0 3 3h12a3 3 0 0 0 3-3V6a3 3 0 0 0-3-3zM6 5h12a1 1 0 0 1 1 1v8.36l-3.2-2.73a2.77 2.77 0 0 0-3.52 0L5 17.7V6a1 1 0 0 1 1-1zm12 14H6.56l7-5.84a.78.78 0 0 1 .93 0L19 17v1a1 1 0 0 1-1 1z\" /> <circle cx=\"8\" cy=\"8.5\" r=\"1.5\" /> </g> </g>" }} />
  );
}
